.TH BUFFALO 1 buffalo\-VERSION
.SH NAME
buffalo \- buffalo buffalo buffalo buffalo buffalo buffalo buffalo
.SH SYNOPSIS
.B buffalo
.SH DESCRIPTION
buffalo is a simple modeless editor that uses it's own replacement for ncurses
(currently called codes). It is still in production so cant do much at all...
